// Generated by https://quicktype.io

export interface Todos {
  total: number
  todos: Todo[]
}

export type Role = {
  name: string
  id: string
}

export interface User {
  uid: string
  email: string
  firstName: string
  lastName?: string
  isActive: boolean
  roles: Role[]
  createdAt: Date
  updatedAt: Date
}

export interface loginResponse {
  user: User
  token: string
}

export interface Todo {
  id: string
  title: string
  description: null
  isActive: boolean
  done: boolean
  createdAt: string
  updatedAt: string
  creator: Creator
}

export interface Creator {
  uid: string
  email: string
  firstName: string
  lastName: null
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface createOrUpdateTodoBody {
  title: string
  description?: string | null
}

export interface login {
  email: string
  password: string
}
