// Generated by https://quicktype.io

export interface Todos {
  total: number
  todos: Todo[]
}

export interface Todo {
  id: string
  title: string
  description: null
  isActive: boolean
  done: boolean
  createdAt: string
  updatedAt: string
  creator: Creator
}

export interface Creator {
  uid: string
  email: string
  firstName: string
  lastName: null
  isActive: boolean
  createdAt: string
  updatedAt: string
}
